# Change these first
owner: opensourcebangladesh # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: BeastsBay
    url: https://beastsbay.com
  - name: ProFishingKit
    url: https://profishingkit.com
  - name: Nextshop.com.bd
    url: https://www.nextshop.com.bd
  - name: Abu sayed
    url: https://abusayed.dev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /status
  cname: status.abusayed.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status 
  introTitle: "Website for monitoring uptime"
  introMessage: Just a website!
  navbar:
    - title: Status
      href: /


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
